---
- name: performing rake tasks (with direnv)
  run_once: "{{ deploy_rake_tasks_run_once }}"
  command: "direnv exec . bundle exec {{ deploy_rake_tasks_command }} {{ item }}"
  args:
    chdir: "{{ deploy_release_dir }}"
  with_items: "{{ deploy_rake_tasks }}"
  when: deploy_with_environment is defined

- name: performing rake tasks (without direnv)
  run_once: "{{ deploy_rake_tasks_run_once }}"
  command: "bundle exec {{ deploy_rake_tasks_command }} {{ item }}"
  args:
    chdir: "{{ deploy_release_dir }}"
  with_items: "{{ deploy_rake_tasks }}"
  when: deploy_with_environment is not defined
